Gisdk error executing function RedrawMap(())
Traceback (most recent call last):
  File "C:\Users\armando\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\caliperpy\caliper3.py", line 612, in __gisdk_function
    o = self.__obj.RunMacro(function_name, *(_list(arg) for arg in args))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<COMObject Maptitude.AutomationServer>", line 4, in RunMacro
  File "C:\Users\armando\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\win32com\client\dynamic.py", line 366, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Maptitude.AutomationServer', 'Wrong number of arguments to function RedrawMap. Expected 1 to 2, found 0.', None, 0, -2147352567), None)
